# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1df1b64b21c56c28e13a760641886cdf"
name = "kaka"
handle = "kaka-8"
application_url = "https://louisiana-wm-alt-plates.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://louisiana-wm-alt-plates.trycloudflare.com/auth/callback",
  "https://louisiana-wm-alt-plates.trycloudflare.com/auth/shopify/callback",
  "https://louisiana-wm-alt-plates.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[extensions.theme-app-extension]
name = "AI Storybook Generator"
handle = "ai-storybook-generator"
